# Generated by Django 3.0.5 on 2020-05-20 17:06

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='uuid')),
                ('is_trash', models.BooleanField(default=False, editable=False, verbose_name='trash')),
                ('trashed_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('pid', models.CharField(blank=True, help_text='Personal Identifier Number', max_length=256, null=True, verbose_name='PID')),
                ('gender', models.CharField(choices=[('L', 'Male'), ('P', 'Female')], default='L', max_length=1, verbose_name='gender')),
                ('date_of_birth', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='date of birth')),
                ('place_of_birth', models.CharField(blank=True, max_length=255, null=True, verbose_name='place of birth')),
                ('privacy', models.CharField(choices=[('anyone', 'Anyone'), ('users', 'All Users'), ('friends', 'All Friends'), ('students', 'All Students'), ('teachers', 'All Teachers'), ('employees', 'All Employees'), ('managers', 'All Managers'), ('me', 'Only Me')], default='anyone', help_text='Designates who can see this information.', max_length=128, verbose_name='privacy')),
                ('nickname', models.CharField(blank=True, max_length=256, null=True, verbose_name='nick name')),
                ('about_me', models.TextField(blank=True, max_length=128, null=True, verbose_name='about me')),
                ('religion', models.CharField(blank=True, max_length=255, null=True, verbose_name='religion')),
                ('nation', models.CharField(blank=True, max_length=255, null=True, verbose_name='nation')),
                ('trashed_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person_trashes', to=settings.AUTH_USER_MODEL, verbose_name='trashed by')),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'Persons',
            },
        ),
        migrations.CreateModel(
            name='Working',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='uuid')),
                ('is_trash', models.BooleanField(default=False, editable=False, verbose_name='trash')),
                ('trashed_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('institution', models.CharField(max_length=256, verbose_name='institution')),
                ('date_start', models.DateField(default=django.utils.timezone.now, verbose_name='date start')),
                ('date_end', models.DateField(default=django.utils.timezone.now, verbose_name='date end')),
                ('document_link', models.URLField(blank=True, help_text='Provide support document link', null=True, verbose_name='document link')),
                ('privacy', models.CharField(choices=[('anyone', 'Anyone'), ('users', 'All Users'), ('friends', 'All Friends'), ('students', 'All Students'), ('teachers', 'All Teachers'), ('employees', 'All Employees'), ('managers', 'All Managers'), ('me', 'Only Me')], default='anyone', help_text='Designates who can see this information.', max_length=128, verbose_name='privacy')),
                ('department', models.CharField(max_length=256, verbose_name='department')),
                ('position', models.CharField(max_length=256, verbose_name='position')),
                ('description', models.TextField(blank=True, max_length=256, null=True, verbose_name='description')),
                ('employment', models.CharField(choices=[('CTR', 'Contract'), ('FXD', 'Fixed'), ('OSR', 'Outsource'), ('ELS', 'Else')], default='CTR', max_length=5, verbose_name='employment')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_histories', to='example.Person')),
                ('trashed_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='working_trashes', to=settings.AUTH_USER_MODEL, verbose_name='trashed by')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='uuid')),
                ('is_trash', models.BooleanField(default=False, editable=False, verbose_name='trash')),
                ('trashed_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('organization', models.CharField(max_length=256, verbose_name='organization')),
                ('position', models.CharField(max_length=256, verbose_name='position')),
                ('description', models.TextField(max_length=256, verbose_name='description')),
                ('date_start', models.DateField(default=django.utils.timezone.now, verbose_name='date start')),
                ('date_end', models.DateField(default=django.utils.timezone.now, verbose_name='date end')),
                ('status', models.CharField(choices=[('ACT', 'Active'), ('INC', 'Inactive')], default='ACT', max_length=5, verbose_name='status')),
                ('document_link', models.URLField(blank=True, help_text='Provide support document link', null=True, verbose_name='document link')),
                ('privacy', models.CharField(choices=[('anyone', 'Anyone'), ('users', 'All Users'), ('friends', 'All Friends'), ('students', 'All Students'), ('teachers', 'All Teachers'), ('employees', 'All Employees'), ('managers', 'All Managers'), ('me', 'Only Me')], default='anyone', help_text='Designates who can see this information.', max_length=128, verbose_name='privacy')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteers', to='example.Person')),
                ('trashed_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_trashes', to=settings.AUTH_USER_MODEL, verbose_name='trashed by')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.SlugField(blank=True, help_text='Facebook page or name', null=True)),
                ('twitter', models.SlugField(blank=True, help_text='Twitter username, without the @', max_length=255, null=True)),
                ('instagram', models.SlugField(blank=True, help_text='Instagram username, without the @', max_length=255, null=True)),
                ('youtube', models.SlugField(blank=True, help_text='Youtube channel name.', null=True)),
                ('privacy', models.CharField(choices=[('anyone', 'Anyone'), ('users', 'All Users'), ('friends', 'All Friends'), ('students', 'All Students'), ('teachers', 'All Teachers'), ('employees', 'All Employees'), ('managers', 'All Managers'), ('me', 'Only Me')], default='anyone', help_text='Designates who can see this information.', max_length=128, verbose_name='privacy')),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='social_media', to='example.Person')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='uuid')),
                ('is_trash', models.BooleanField(default=False, editable=False, verbose_name='trash')),
                ('trashed_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=256, verbose_name='name')),
                ('description', models.CharField(blank=True, max_length=256, null=True, verbose_name='description')),
                ('level', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Skill level')),
                ('privacy', models.CharField(choices=[('anyone', 'Anyone'), ('users', 'All Users'), ('friends', 'All Friends'), ('students', 'All Students'), ('teachers', 'All Teachers'), ('employees', 'All Employees'), ('managers', 'All Managers'), ('me', 'Only Me')], default='anyone', help_text='Designates who can see this information.', max_length=128, verbose_name='privacy')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='example.Person')),
                ('trashed_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skill_trashes', to=settings.AUTH_USER_MODEL, verbose_name='trashed by')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='uuid')),
                ('is_trash', models.BooleanField(default=False, editable=False, verbose_name='trash')),
                ('trashed_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('title', models.CharField(max_length=256, verbose_name='title')),
                ('description', models.CharField(blank=True, max_length=256, null=True, verbose_name='description')),
                ('publisher', models.CharField(blank=True, max_length=256, null=True, verbose_name='publisher')),
                ('date_published', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='published date')),
                ('document_link', models.URLField(blank=True, help_text='provide support document link', null=True, verbose_name='document link')),
                ('privacy', models.CharField(choices=[('anyone', 'Anyone'), ('users', 'All Users'), ('friends', 'All Friends'), ('students', 'All Students'), ('teachers', 'All Teachers'), ('employees', 'All Employees'), ('managers', 'All Managers'), ('me', 'Only Me')], default='anyone', help_text='Designates who can see this information.', max_length=128, verbose_name='privacy')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='example.Person')),
                ('trashed_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publication_trashes', to=settings.AUTH_USER_MODEL, verbose_name='trashed by')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PersonContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=128, null=True, verbose_name='phone')),
                ('fax', models.CharField(blank=True, max_length=128, null=True, verbose_name='fax')),
                ('email', models.CharField(blank=True, help_text='your public email', max_length=128, null=True, verbose_name='email')),
                ('whatsapp', models.CharField(blank=True, max_length=128, null=True, verbose_name='whatsapp')),
                ('website', models.CharField(blank=True, max_length=128, null=True, verbose_name='website')),
                ('privacy', models.CharField(choices=[('anyone', 'Anyone'), ('users', 'All Users'), ('friends', 'All Friends'), ('students', 'All Students'), ('teachers', 'All Teachers'), ('employees', 'All Employees'), ('managers', 'All Managers'), ('me', 'Only Me')], default='anyone', help_text='Designates who can see this information.', max_length=128, verbose_name='privacy')),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contact', to='example.Person')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PersonAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=True, verbose_name='primary')),
                ('name', models.CharField(choices=[('home', 'Home'), ('office', 'Office')], default='home', help_text='E.g. Home Address or Office Address', max_length=256, null=True, verbose_name='name')),
                ('street', models.CharField(blank=True, max_length=512, null=True, verbose_name='street')),
                ('city', models.CharField(blank=True, max_length=128, null=True, verbose_name='city')),
                ('province', models.CharField(blank=True, max_length=128, null=True, verbose_name='province')),
                ('country', models.CharField(blank=True, max_length=128, null=True, verbose_name='country')),
                ('zipcode', models.CharField(blank=True, max_length=128, null=True, verbose_name='zip code')),
                ('privacy', models.CharField(choices=[('anyone', 'Anyone'), ('users', 'All Users'), ('friends', 'All Friends'), ('students', 'All Students'), ('teachers', 'All Teachers'), ('employees', 'All Employees'), ('managers', 'All Managers'), ('me', 'Only Me')], default='anyone', help_text='Designates who can see this information.', max_length=128, verbose_name='privacy')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='example.Person')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NonFormalEducation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='uuid')),
                ('is_trash', models.BooleanField(default=False, editable=False, verbose_name='trash')),
                ('trashed_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('institution', models.CharField(max_length=256, verbose_name='institution')),
                ('date_start', models.DateField(default=django.utils.timezone.now, verbose_name='date start')),
                ('date_end', models.DateField(default=django.utils.timezone.now, verbose_name='date end')),
                ('document_link', models.URLField(blank=True, help_text='Provide support document link', null=True, verbose_name='document link')),
                ('privacy', models.CharField(choices=[('anyone', 'Anyone'), ('users', 'All Users'), ('friends', 'All Friends'), ('students', 'All Students'), ('teachers', 'All Teachers'), ('employees', 'All Employees'), ('managers', 'All Managers'), ('me', 'Only Me')], default='anyone', help_text='Designates who can see this information.', max_length=128, verbose_name='privacy')),
                ('description', models.CharField(blank=True, max_length=256, null=True, verbose_name='description')),
                ('status', models.CharField(choices=[('FNS', 'Finished'), ('ONG', 'Ongoing'), ('UNF', 'Unfinished')], default='ONG', max_length=5, verbose_name='current status')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='non_formal_educations', to='example.Person')),
                ('trashed_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nonformaleducation_trashes', to=settings.AUTH_USER_MODEL, verbose_name='trashed by')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FormalEducation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='uuid')),
                ('is_trash', models.BooleanField(default=False, editable=False, verbose_name='trash')),
                ('trashed_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('institution', models.CharField(max_length=256, verbose_name='institution')),
                ('date_start', models.DateField(default=django.utils.timezone.now, verbose_name='date start')),
                ('date_end', models.DateField(default=django.utils.timezone.now, verbose_name='date end')),
                ('document_link', models.URLField(blank=True, help_text='Provide support document link', null=True, verbose_name='document link')),
                ('privacy', models.CharField(choices=[('anyone', 'Anyone'), ('users', 'All Users'), ('friends', 'All Friends'), ('students', 'All Students'), ('teachers', 'All Teachers'), ('employees', 'All Employees'), ('managers', 'All Managers'), ('me', 'Only Me')], default='anyone', help_text='Designates who can see this information.', max_length=128, verbose_name='privacy')),
                ('major', models.CharField(blank=True, help_text='ex: Information System or Accounting', max_length=256, null=True, verbose_name='major')),
                ('status', models.CharField(choices=[('FNS', 'Finished'), ('ONG', 'Ongoing'), ('UNF', 'Unfinished')], default='ONG', max_length=5, verbose_name='current status')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formal_educations', to='example.Person')),
                ('trashed_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formaleducation_trashes', to=settings.AUTH_USER_MODEL, verbose_name='trashed by')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='uuid')),
                ('is_trash', models.BooleanField(default=False, editable=False, verbose_name='trash')),
                ('trashed_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('relation', models.PositiveIntegerField(choices=[(1, 'Father'), (2, 'Mother'), (5, 'Husband'), (6, 'Wife'), (4, 'Children'), (3, 'Sibling'), (99, 'Other')], default=99, verbose_name='relation')),
                ('relationship', models.CharField(blank=True, max_length=256, null=True, verbose_name='other relation')),
                ('name', models.CharField(max_length=256, verbose_name='name')),
                ('date_of_birth', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='date of birth')),
                ('place_of_birth', models.CharField(blank=True, max_length=255, null=True, verbose_name='place of birth')),
                ('job', models.CharField(max_length=256, verbose_name='job')),
                ('address', models.TextField(blank=True, max_length=512, null=True, verbose_name='address')),
                ('privacy', models.CharField(choices=[('anyone', 'Anyone'), ('users', 'All Users'), ('friends', 'All Friends'), ('students', 'All Students'), ('teachers', 'All Teachers'), ('employees', 'All Employees'), ('managers', 'All Managers'), ('me', 'Only Me')], default='anyone', help_text='Designates who can see this information.', max_length=128, verbose_name='privacy')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='families', to='example.Person')),
                ('trashed_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='family_trashes', to=settings.AUTH_USER_MODEL, verbose_name='trashed by')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='uuid')),
                ('is_trash', models.BooleanField(default=False, editable=False, verbose_name='trash')),
                ('trashed_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=256, verbose_name='name')),
                ('description', models.TextField(blank=True, max_length=256, null=True, verbose_name='description')),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='created date')),
                ('document_link', models.URLField(blank=True, help_text='Provide support document link', null=True, verbose_name='document link')),
                ('privacy', models.CharField(choices=[('anyone', 'Anyone'), ('users', 'All Users'), ('friends', 'All Friends'), ('students', 'All Students'), ('teachers', 'All Teachers'), ('employees', 'All Employees'), ('managers', 'All Managers'), ('me', 'Only Me')], default='anyone', help_text='Designates who can see this information.', max_length=128, verbose_name='privacy')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='example.Person')),
                ('trashed_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='award_trashes', to=settings.AUTH_USER_MODEL, verbose_name='trashed by')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
